### ISSUE TITLE
WIN Instant auction - notification

### ISSUE THREAD

**Issue by ryanprice** [Cardinal-Entertainment/nft-market#169]
Steps to repeat. go to **http://localhost:3000/moonbase-alpha** and click on any of the Buy Now ( green button ) auctions. Observe the notification feed, after tx confirmation.

When I bid  AND win to close an instant auction. I incorrectly receive an event notification to overbid myself.
The correct notification, for the winner, should be that they have successfully WON the auction

.ie:
Auction 12
You have WON this auction
Bid Amount: 0.021
( and display the trophy icon)

For all observers, a notification that the auction was WON by 0xnnnnnnnnn   wallet

Can keep this, and add a additional notification
![image](https://user-images.githubusercontent.com/180252/165814046-15e716b7-a3bc-4a16-b95d-82d9b2adcae7.png)

These are incorrect
![image](https://user-images.githubusercontent.com/180252/156400122-903400eb-e05c-4049-9b10-1a1510189b89.png)

**Comment by mchigit** [comment]
https://github.com/Cardinal-Entertainment/nft-market/pull/213
