### ISSUE TITLE
feed notification icon for Zoom is incorrect

### ISSUE THREAD

**Issue by ryanprice** [Cardinal-Entertainment/nft-market#207]
I bid 60,000 Zoom and the feed notification, has correct token amount, with incorrect icon

![image](https://user-images.githubusercontent.com/180252/167760463-3ada9f07-1944-4058-8609-0b4abe44959e.png)

**Comment by mchigit** [comment]
Actually I just realized, the bid event doesn't actually contain data on which currency it is, or the original `saleToken`. So we are defaulting to movr icon all the time. There are 2 ways of going about this:

1. The hacky way (not really good for our server) is I can make query to our API to get the listing item for each bid and check for currency
2. The better way is for the bid event to start emitting currency data. But this will require us to clear the DB and re-scrape all data

**Comment by mchigit** [comment]
https://github.com/Cardinal-Entertainment/nft-market/pull/213
